sudo: required

language: node_js
node_js:
  - "10.4.1"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker build -t rootdevelopper/docker-angular -f Dockerfile.dev .

before_script:
  - npm install

script:
  - docker run -e rootdevelopper/docker-angular npm run test-headless

